### ISSUE TITLE
Curry v4.0.0 pod install issue

### ISSUE THREAD

**Issue by vicky-digiapt** [thoughtbot/Curry#44] opened 2017-12-28 13:12 UTC
The latest release by curry is unable to be installed via PodFile.

My PodFile contains  **pod 'Curry', '4.0.0'**

When I execute _pod install_ I get the following error shown in the image.

![screen shot 2017-12-28 at 6 14 21 pm](https://user-images.githubusercontent.com/28340233/34411648-07f07866-ebfe-11e7-8eee-cd72233564c3.png)

**Comment by GregoryMaks** [comment] 2017-12-28 13:19
`pod search` gives us

```-> Curry (3.0.0)
   Function Currying for Swift
   pod 'Curry', '~> 3.0.0'
   - Homepage: https://github.com/thoughtbot/curry
   - Source:   https://github.com/thoughtbot/curry.git
   - Versions: 3.0.0, 2.3.3, 2.3.1, 2.3.0, 2.2.0, 2.1.0, 2.0.0, 1.4.0, 1.3.0, 1.2.0, 1.1.1, 1.1.0, 1.0.0 [master repo]
```

Looks like the latest podspec is still not pushed to Cocoapods repo 😞

**Comment by vicky-digiapt** [comment] 2017-12-28 13:21
Yes. Hopefully they update the master branch soon. 

Am unable to use Curry in Xcode 9+ because of no swift4 support in v3.0.0

**Comment by gfontenot** [comment] 2017-12-30 01:50
This is a duplicate of #43. I'm working on restoring my ability to update CocoaPods Trunk, but for now you should be able to point at master and get support for Swift 4.0.

**Closed as completed by gfontenot** 2017-12-30 01:50 UTC
